on:
  schedule:
    - cron: '0 0 * * 0,3'
  push:
    branches:
      - 'master'

name: "Build And Push PHP Docker Images"

jobs:
  build-and-push-docker:
    name: "Build And Push PHP Docker Images"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        php-target:
          - "cli"
          - "fpm"
          - "zts"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Install Docker Composer 2.x"
        run: |
          curl -fL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh | sudo sh
          sudo  update-alternatives --display docker-compose
          docker -v
          docker-compose -v

      - name: "Build ${{ matrix.php-target }} ${{ matrix.php-version }}"
        working-directory: php
        env:
          PHP_VERSION: ${{ matrix.php-version }}
          PHP_TARGET: ${{ matrix.php-target }}
          DOCKER_REGISTRY: "prooph/docker-files/"
        run: docker-compose build

      - name: "Login GitHub package registry"
        working-directory: php
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login ghcr.io -u $DOCKER_USERNAME -p "$DOCKER_TOKEN"

      - name: "Push images"
        working-directory: php
        env:
          PHP_VERSION: ${{ matrix.php-version }}
          PHP_TARGET: ${{ matrix.php-target }}
          DOCKER_REGISTRY: "prooph/docker-files/"
        run: "docker-compose push"

      - name: "Push Composer"
        working-directory: php
        env:
          PHP_VERSION: ${{ matrix.php-version }}
          PHP_TARGET: ${{ matrix.php-target }}
          DOCKER_REGISTRY: "prooph/docker-files/"
        if: ${{ matrix.php-target }} == 'cli'
        run: |
          docker tag ${DOCKER_REGISTRY}composer:${PHP_VERSION}-${PHP_TARGET} ${DOCKER_REGISTRY}composer:${PHP_VERSION}
          docker push ${DOCKER_REGISTRY}composer:${PHP_VERSION}

      - name: "Cleanup"
        run: rm /home/runner/.docker/config.json
